# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - main

pool:
  name: SelfHostedPool

jobs:

- job: BuildAndRun
  steps:
  - script: dotnet build HelloWorldApp.csproj
    displayName: 'Build HelloWorldApp'

  - script: dotnet test HelloWorldApp.csproj
    displayName: 'Test HelloWorldApp'

- job: DockerImageBuildAndRun
  steps:
  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      command: build
      Dockerfile: '**/Dockerfile'
      repository: 'HelloWorldApp'
      tags: 'latest'

  - script: |
      echo "Running the Docker container..."
      docker run helloworldapp:latest
    displayName: Run Docker Container
    
# steps:
# - script: dotnet build HelloWorldApp.csproj
#   displayName: 'Build HelloWorldApp'

# - script: dotnet test HelloWorldApp.csproj
#   displayName: 'Test HelloWorldApp'
